name: Build & Test in DevVer and SIT

env:
  ACTIONS_STEP_DEBUG: true

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]
  workflow_dispatch:

jobs:
  DevVer:
    runs-on: [self-hosted]
    strategy:
      matrix:
        browser: [ brave ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache JDK
        uses: actions/cache@v3
        with:
          path: /home/eric/actions-runner2/_work/_tool/Java_Temurin-Hotspot_jdk/19.0.2-7/x64
          key: ${{ runner.os }}-jdk19-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-jdk19-

      - name: Start timing
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV

      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: 'maven'
          path: /home/eric/actions-runner2/_work/_tool/Java_Temurin-Hotspot_jdk/19.0.2-7/x64

      - name: End timing
        run: |
          END_TIME=$(date +%s)
          echo "Process took $((END_TIME - START_TIME)) seconds to complete"

      - name: Start timing
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV
      - name: Build & Test DevVer with Maven
        run: mvn -B test  -D browser=${{ matrix.browser }} --file pom.xml
      - name: End timing
        run: |
          END_TIME=$(date +%s)
          echo "Process took $((END_TIME - START_TIME)) seconds to complete"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: DevVer test results ${{ matrix.browser }} - ${{ github.run_id }}
          path: target/surefire-reports/

  DevInt:
    runs-on: [self-hosted]
    needs: DevVer
    strategy:
      matrix:
        browser: [ chrome ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache JDK
        uses: actions/cache@v3
        with:
          path: /home/eric/actions-runner2/_work/_tool/Java_Temurin-Hotspot_jdk/19.0.2-7/x64
          key: ${{ runner.os }}-jdk19-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-jdk19-

      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: 'maven'
          path: /home/eric/actions-runner2/_work/_tool/Java_Temurin-Hotspot_jdk/19.0.2-7/x64

      - name: Build & Test DevInt with Maven
        run: mvn -B test -D browser=${{ matrix.browser }} --file pom.xml
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: DevInt test results ${{ matrix.browser }} - ${{ github.run_id }}
          path: target/surefire-reports/

  SIT:
    runs-on: [self-hosted]
    needs: DevInt
    strategy:
      matrix:
        browser: [chrome, brave ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache JDK
        uses: actions/cache@v3
        with:
          path: /home/eric/actions-runner2/_work/_tool/Java_Temurin-Hotspot_jdk/19.0.2-7/x64
          key: ${{ runner.os }}-jdk19-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-jdk19-

      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: 'maven'
          path: /home/eric/actions-runner2/_work/_tool/Java_Temurin-Hotspot_jdk/19.0.2-7/x64

      - name: Build & test SIT with Maven
        run: mvn -B test  -D browser=${{ matrix.browser }}  --file pom.xml

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: SIT test results ${{ matrix.browser }} - ${{ github.run_id }}
          path: target/surefire-reports/

  Production:
    runs-on: [self-hosted]
    needs: SIT
    steps:
      - name Done
        run echo "DONE"
